const input_text=document.querySelector("#text");
let listen_box=document.querySelector(".listen");
const content_box=document.querySelector(".content");
function checkEmpty(){
    const text=document.querySelector("#text").value.trim();
    if(text.length==0){
        listen_box.innerHTML=`<i class="fa-solid fa-ear-listen"></i>`;
    }
    else{
        listen_box.innerHTML=`<i class="fa-solid fa-arrow-right"></i>`;
    }
}

listen_box.addEventListener("click", () => {
    if(listen_box.innerHTML.includes("arrow")){
        // Append user input in content
        const userbox_parent = document.createElement("div");
        userbox_parent.classList.add("userparent");
        
        const userbox = document.createElement("div");
        userbox.classList.add("user");
        const text = document.querySelector("#text").value.trim();
        input_text.value="";
        userbox.innerHTML = text;
    
        userbox_parent.appendChild(userbox);
        content_box.appendChild(userbox_parent);
    
        // Create answer container
        const answer = document.createElement("div");
        answer.classList.add("answer");
        content_box.appendChild(answer);
    
        // Add spinner after 500ms
        setTimeout(() => {
            const spinner = document.createElement("div");
            spinner.classList.add("spinner");
            answer.appendChild(spinner);
    
            // Remove spinner and add fetched answer after 4 seconds
            setTimeout(() => {
                answer.removeChild(spinner);
    
                const fetchedAnswer = "Some answer generated by ChatGPT";
                answer.innerText = fetchedAnswer;
            }, 2500); // 4 seconds total (500ms for spinner + 3500ms for answer)
        }, 500);
    }
    else{
        //This will be the voice to text part;
        
    }
});

input_text.addEventListener("input",checkEmpty);
